import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function Terms() {
    return (
        <main className="min-h-screen bg-gray-950 text-white selection:bg-blue-500/30 font-sans">
            <div className="max-w-3xl mx-auto px-6 py-20">
                <Link href="/" className="inline-flex items-center text-gray-400 hover:text-white transition-colors mb-8 group">
                    <ArrowLeft size={20} className="mr-2 group-hover:-translate-x-1 transition-transform" />
                    Back to Home
                </Link>

                <h1 className="text-4xl font-bold mb-6">Terms of Service</h1>

                <div className="space-y-6 text-gray-300 leading-relaxed text-sm">
                    <p>Last updated: February 2026</p>

                    <h2 className="text-xl font-semibold text-white mt-8">1. Acceptance of Terms</h2>
                    <p>
                        By using IdeaSpark AI, you agree to these terms. If you do not agree, please do not use the service.
                    </p>

                    <h2 className="text-xl font-semibold text-white mt-8">2. Use of Service</h2>
                    <p>
                        You may use IdeaSpark AI for personal and commercial idea generation. You are responsible for verifyng the viability of any ideas generated.
                    </p>

                    <h2 className="text-xl font-semibold text-white mt-8">3. AI-Generated Content</h2>
                    <p>
                        The content is generated by Artificial Intelligence. We make no guarantees regarding the accuracy, originality, or legality of the generated ideas.
                    </p>

                    <h2 className="text-xl font-semibold text-white mt-8">4. Disclaimer</h2>
                    <p>
                        The service is provided "as is" without warranties of any kind. We are not liable for any damages arising from the use of this service.
                    </p>
                </div>
            </div>
        </main>
    );
}
